permissions:
  contents: write

name: Release Self-Destructing Cache Extension

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build && npm run zip
      - run: npm run build:edge && npm run zip:edge
      - run: npm run build:firefox && npm run zip:firefox
      - run: npm run build:firefox
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --generate-notes \
            --latest \
            .output\self-destructing-cache-*.zip
